/**
 * GET /api/v1 — Nitro twin of the Express handler in
 * src/modules/api/v1/api.ts. Byte-identical (D3): introspection listing.
 */
import { defineEventHandler } from 'h3'

export default defineEventHandler(() => ({
  data: {
    version: 'v1',
    endpoints: [
      { method: 'GET', path: '/api/v1', description: 'Introspection – list all routes' },
      { method: 'GET', path: '/api/v1/ping', description: 'Health check' },
      { method: 'GET', path: '/api/v1/users', description: 'List users', permission: 'arclight.api.users.read' },
      { method: 'POST', path: '/api/v1/users', description: 'Create a user', permission: 'arclight.api.users.create' },
      { method: 'GET', path: '/api/v1/users/:id', description: 'Get a user', permission: 'arclight.api.users.read' },
      { method: 'PATCH', path: '/api/v1/users/:id', description: 'Update a user', permission: 'arclight.api.users.update' },
      { method: 'DELETE', path: '/api/v1/users/:id', description: 'Delete a user', permission: 'arclight.api.users.delete' },
      { method: 'GET', path: '/api/v1/servers', description: 'List servers', permission: 'arclight.api.servers.read' },
      { method: 'POST', path: '/api/v1/servers', description: 'Create a server', permission: 'arclight.api.servers.create' },
      { method: 'GET', path: '/api/v1/servers/:id', description: 'Get a server', permission: 'arclight.api.servers.read' },
      { method: 'PATCH', path: '/api/v1/servers/:id', description: 'Update a server', permission: 'arclight.api.servers.update' },
      { method: 'POST', path: '/api/v1/servers/:id/suspend', description: 'Suspend a server', permission: 'arclight.api.servers.update' },
      { method: 'POST', path: '/api/v1/servers/:id/unsuspend', description: 'Unsuspend a server', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id', description: 'Delete a server', permission: 'arclight.api.servers.delete' },
      { method: 'GET', path: '/api/v1/nodes', description: 'List nodes', permission: 'arclight.api.nodes.read' },
      { method: 'POST', path: '/api/v1/nodes', description: 'Create a node', permission: 'arclight.api.nodes.create' },
      { method: 'GET', path: '/api/v1/nodes/:id', description: 'Get a node', permission: 'arclight.api.nodes.read' },
      { method: 'PATCH', path: '/api/v1/nodes/:id', description: 'Update a node', permission: 'arclight.api.nodes.update' },
      { method: 'DELETE', path: '/api/v1/nodes/:id', description: 'Delete a node', permission: 'arclight.api.nodes.delete' },
      { method: 'GET', path: '/api/v1/settings', description: 'Get settings', permission: 'arclight.api.settings.read' },
      { method: 'PATCH', path: '/api/v1/settings', description: 'Update settings', permission: 'arclight.api.settings.update' },
      { method: 'GET', path: '/api/v1/servers/:id/backups', description: 'List backups', permission: 'arclight.api.servers.read' },
      { method: 'POST', path: '/api/v1/servers/:id/backups', description: 'Create a backup', permission: 'arclight.api.servers.update' },
      { method: 'POST', path: '/api/v1/servers/:id/backups/:backupId/restore', description: 'Restore a backup', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id/backups/:backupId', description: 'Delete a backup', permission: 'arclight.api.servers.update' },
      { method: 'GET', path: '/api/v1/servers/:id/databases', description: 'List databases', permission: 'arclight.api.servers.read' },
      { method: 'POST', path: '/api/v1/servers/:id/databases', description: 'Create a database', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id/databases/:dbId', description: 'Delete a database', permission: 'arclight.api.servers.update' },
      { method: 'GET', path: '/api/v1/servers/:id/subusers', description: 'List subusers', permission: 'arclight.api.servers.read' },
      { method: 'POST', path: '/api/v1/servers/:id/subusers', description: 'Add a subuser', permission: 'arclight.api.servers.update' },
      { method: 'PATCH', path: '/api/v1/servers/:id/subusers/:subUserId', description: 'Update subuser permissions', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id/subusers/:subUserId', description: 'Remove a subuser', permission: 'arclight.api.servers.update' },
      { method: 'GET', path: '/api/v1/servers/:id/startup', description: 'Get server startup', permission: 'arclight.api.servers.read' },
      { method: 'PATCH', path: '/api/v1/servers/:id/startup', description: 'Update server startup', permission: 'arclight.api.servers.update' },
      { method: 'GET', path: '/api/v1/servers/:id/schedules', description: 'List schedules', permission: 'arclight.api.servers.read' },
      { method: 'POST', path: '/api/v1/servers/:id/schedules', description: 'Create a schedule', permission: 'arclight.api.servers.update' },
      { method: 'PATCH', path: '/api/v1/servers/:id/schedules/:scheduleId', description: 'Update a schedule', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id/schedules/:scheduleId', description: 'Delete a schedule', permission: 'arclight.api.servers.update' },
      { method: 'POST', path: '/api/v1/servers/:id/schedules/:scheduleId/tasks', description: 'Add a schedule task', permission: 'arclight.api.servers.update' },
      { method: 'DELETE', path: '/api/v1/servers/:id/schedules/:scheduleId/tasks/:taskId', description: 'Delete a schedule task', permission: 'arclight.api.servers.update' },
      { method: 'GET', path: '/api/v1/nodes/:id/allocations', description: 'List node allocations', permission: 'arclight.api.nodes.read' },
      { method: 'POST', path: '/api/v1/nodes/:id/allocations', description: 'Add a node allocation', permission: 'arclight.api.nodes.update' },
      { method: 'DELETE', path: '/api/v1/nodes/:id/allocations/:allocationId', description: 'Delete a node allocation', permission: 'arclight.api.nodes.update' },
      { method: 'GET', path: '/api/v1/images', description: 'List images', permission: 'arclight.api.images.read' },
      { method: 'POST', path: '/api/v1/images', description: 'Create an image', permission: 'arclight.api.images.create' },
      { method: 'GET', path: '/api/v1/images/:id', description: 'Get an image', permission: 'arclight.api.images.read' },
      { method: 'PATCH', path: '/api/v1/images/:id', description: 'Update an image', permission: 'arclight.api.images.update' },
      { method: 'DELETE', path: '/api/v1/images/:id', description: 'Delete an image', permission: 'arclight.api.images.delete' },
      { method: 'GET', path: '/api/v1/locations', description: 'List locations', permission: 'arclight.api.locations.read' },
      { method: 'POST', path: '/api/v1/locations', description: 'Create a location', permission: 'arclight.api.locations.create' },
    ],
  },
}))
