import { createFileRoute, Link } from '@tanstack/react-router'
import { useEffect, useState } from 'react'

import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { AuthLayout } from '@/components/auth/auth-layout'
import { useAuthConfig, isAuthenticatedUser, DEFAULT_SETTINGS } from '@/lib/auth-config'
import { submitLogin } from '@/lib/auth'
import { loginErrorMessage } from '@/lib/errors'
import { queryClient } from '@/lib/query-client'
import { cn } from '@/lib/utils'

export const Route = createFileRoute('/login')({
  validateSearch: (search: Record<string, unknown>) =>
    ({ err: typeof search.err === 'string' ? search.err : undefined }) as {
      err?: string
    },
  component: LoginPage,
})

function LoginPage() {
  const { err } = Route.useSearch()
  const navigate = Route.useNavigate()
  const auth = useAuthConfig()

  const [identifier, setIdentifier] = useState('')
  const [password, setPassword] = useState('')
  const [remember, setRemember] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  // Show a redirect-provided error (e.g. ?err=reset_email_sent from the
  // password reset flow, or ?err=registration_disabled).
  useEffect(() => {
    if (err) {
      setError(loginErrorMessage(err))
    }
  }, [err])

  // Already signed in? Skip the login form.
  useEffect(() => {
    if (auth.isSuccess && isAuthenticatedUser(auth.data.user)) {
      navigate({ to: '/' })
    }
  }, [auth.isSuccess, auth.data?.user, navigate])

  const settings = auth.data?.settings

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      const outcome = await submitLogin({
        identifier: identifier.trim(),
        password,
        remember,
        csrfToken: auth.data?.csrfToken ?? null,
      })
      if (outcome.type === 'success') {
        // Drop cached auth state so the destination page fetches the fresh
        // post-login session (the session cookie was regenerated by Express).
        queryClient.removeQueries({ queryKey: ['auth-config'] })
        navigate({ to: outcome.path as '/' | '/2fa' })
        return
      }
      setError(outcome.message)
    } catch {
      setError('Something went wrong. Try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthLayout
      title="Sign in"
      subtitle={settings?.title ? `to ${settings.title}` : undefined}
      settings={settings ?? DEFAULT_SETTINGS}
      error={error}
      footer={
        settings?.allowRegistration ? (
          <p>
            Don&apos;t have an account?{' '}
            <Link to="/register" className="font-medium text-primary hover:underline">
              Create one
            </Link>
          </p>
        ) : null
      }
    >
      <form onSubmit={onSubmit} className="space-y-4" autoComplete="on" noValidate>
        <div className="space-y-2">
          <Label htmlFor="identifier">Username or email</Label>
          <Input
            id="identifier"
            name="identifier"
            type="text"
            autoComplete="username"
            required
            spellCheck={false}
            autoCapitalize="none"
            placeholder="you@example.com"
            value={identifier}
            onChange={(e) => setIdentifier(e.target.value)}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <div className="relative">
            <Input
              id="password"
              name="password"
              type={showPassword ? 'text' : 'password'}
              autoComplete="current-password"
              required
              placeholder="••••••••"
              className="pr-10"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <button
              type="button"
              onClick={() => setShowPassword((v) => !v)}
              className="absolute inset-y-0 right-0 flex items-center px-3 text-muted-foreground hover:text-foreground"
              aria-label={showPassword ? 'Hide password' : 'Show password'}
            >
              {showPassword ? <EyeOffIcon /> : <EyeIcon />}
            </button>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <Label htmlFor="remember" className="cursor-pointer gap-2 text-sm font-normal text-muted-foreground">
            <Checkbox
              id="remember"
              checked={remember}
              onCheckedChange={(checked) => setRemember(checked === true)}
            />
            Remember me
          </Label>
          <Link to="/forgot-password" className="text-xs text-muted-foreground hover:text-foreground">
            Forgot password?
          </Link>
        </div>

        <Button type="submit" className="relative w-full" disabled={loading}>
          <span className={cn(loading && 'opacity-0')}>Sign in</span>
          {loading ? <span className="absolute size-4 animate-spin rounded-full border-2 border-background border-t-transparent" /> : null}
        </Button>
      </form>
    </AuthLayout>
  )
}

function EyeIcon() {
  return (
    <svg className="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M2.06 12.35a1 1 0 0 1 0-.7 10.75 10.75 0 0 1 19.88 0 1 1 0 0 1 0 .7 10.75 10.75 0 0 1-19.88 0" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}

function EyeOffIcon() {
  return (
    <svg className="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M10.73 5.08A10.75 10.75 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68" />
      <path d="M6.61 6.61A13.53 13.53 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61" />
      <line x1="2" x2="22" y1="2" y2="22" />
    </svg>
  )
}